#pragma once

#ifdef AW_PLATFORM_WINDOWS
#define VK_USE_PLATFORM_WIN32_KHR
#elif defined(AW_PLATFORM_LINUX)
#define VK_USE_PLATFORM_XCB_KHR
#elif defined(AW_PLATFORM_MACOS)
#define VK_USE_PLATFORM_MACOS_MVK
#endif


#define AW_ENGINE_GRAPHICS_API_VULKAN
// #define AW_ENGINE_GRAPHICS_API_OPENGL